Update node checks
StackStorm/hubot-stackstorm pull request #218
Opened 2021-05-11 22:05 UTC by amanda11

Update to check against node  > 12

2021-05-11 22:29 UTC, blag requested changes
Looks good, although I'd like to minimize our test matrix as well (eg: remove tests for Node < 10) and force us to pass on more up-to-date pinned Node versions.

2021-05-11 22:29 UTC, blag commented on .travis.yml
> +    - node_js: "14"
```suggestion
```

We should force these to pass from now on.

2021-05-12 09:27 UTC, amanda11 commented
@blag - thanks for review. Shorted test matrix, am I ok to leave hubot-stackstorm version as before as not changed anything in the actual package?

2021-05-12 20:53 UTC, blag commented
For this change, that's correct - we do not need to bump and push a new version to NPM, as this is just testing changes.

If we update dependencies, like all of @dependabot's PRs, we should bump the version. But we can "batch" those together with respect to versioning - in other words, we can merge in multiple dependency updates before we bump the version and push it to NPM.

2021-05-12 20:54 UTC, blag approved these changes

2021-05-12 20:56 UTC, merged